
"""add created_at and updated_at to users

Revision ID: 0fcacaa6cba2
Revises: 98252fef952c
Create Date: 2025-07-25 14:13:40.141415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0fcacaa6cba2'
down_revision = 'a7f23d764d38'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
