
"""remove_role_table_use_casbin_only

Revision ID: 7d8dc00eb31f
Revises: cbde839f9979
Create Date: 2025-08-04 14:18:04.387739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d8dc00eb31f'
down_revision: Union[str, None] = 'cbde839f9979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除Role表和相关的外键约束
    # 注意：在删除表之前，确保所有角色信息已经迁移到casbin_rule表
    
    # 如果存在user_roles关联表，先删除它
    op.execute("SET FOREIGN_KEY_CHECKS = 0")
    
    try:
        # 尝试删除user_roles表（如果存在）
        op.drop_table('user_roles')
        print("删除了 user_roles 表")
    except:
        print("user_roles 表不存在，跳过")
    
    try:
        # 删除roles表
        op.drop_table('roles')
        print("删除了 roles 表")
    except:
        print("roles 表不存在，跳过")
    
    op.execute("SET FOREIGN_KEY_CHECKS = 1")
    
    print("✅ 迁移到纯Casbin角色管理系统完成")
    print("所有角色和权限现在通过 casbin_rule 表管理")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 重新创建roles表（用于回滚）
    op.create_table('roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    
    print("⚠️  已恢复 roles 表")
    print("需要手动从 casbin_rule 表恢复角色数据")
    # ### end Alembic commands ###
